### ISSUE TITLE
Wrong number of mouse buttons

### ISSUE THREAD

**Issue by vrkgtpwmvz** [Mischa-Alff/imgui-backends#7]
In imgui-events-SFML.h, line 13 should be:

```
static bool ImImpl_mousePressed[5] = { false, false, false, false, false };
```

bacouse SFML handles five mouse buttons. Having that array of lenght 2 instead of 5 would result in an error when pressing Mouse Middle, Mouse4 or Mouse5.

**Comment by Mischa-Alff** [comment]
You could have made a pull request for this one. 
This will be fixed in the next push. At this point it would probably be less buggy for you to adapt imgui's legacy GL GLFW example to SFML rather than use imgui-backends. I don't use SFML anymore and this repository probably won't be getting too much attention from me in the future.

**Comment by vrkgtpwmvz** [comment]
If that's the case, I don't want to force anything on you. Thanks for your help!.
